#!/bin/sh
#declare -a mmh_exports
#function export_var {
#  local 
#}
# MMH environment settings
function load_mmh_env {
  export SEARS_ROOT=$SOURCECODE/sears
  export MMH_ROOT=$SEARS_ROOT/mmh
  export MMH_HOME=$MMH_ROOT/mmh
  export MMH_HOME_RAILS=$MMH_HOME/mmh-web-mvn/src/main/webapp/rails
  export JRUBY_HOME=$SEARS_ROOT/vendor/jruby
  export PATH=$MMH_ROOT/tools/maven-2.2.1/bin:$PATH:$JRUBY_HOME/bin
  export JBOSS_HOME=$MMH_ROOT/tools/jboss-eap-4.3/jboss-as
  export app_lifecycle=dev 
  export CATALINA_HOME=$MMH_ROOT/tools/apache-tomcat-5.5.20/ 

  platform=$(uname)
  if [ "$platform" == "Darwin" ]; then
    export MAVEN_OPTS="-Xmx1024m"
    os_version=`sw_vers | sed -n '/^ProductVersion:/ { s/^.*\:\s\([0-9]\+\.[0-9]\+\).*$/\1/; p }'`
    if [ "$os_version" == "10.6" ]; then # snow leopard
      MMH_RAILS_BUILD_JAVA_MEM=-Xmx768m
      MMH_RAILS_BUILD_JAVA_OPTS="-d32 -XX:MaxPermSize=768m"
    elif [ "$os_version" == "10.5" ]; then # leopard
      MMH_RAILS_BUILD_JAVA_MEM=-Xmx2048m
      MMH_RAILS_BUILD_JAVA_OPTS="-XX:MaxPermSize=2048m"
    else
      echo "Error: Unsupported OS version - $os_version"
      exit 1
    fi
    export MMH_RAILS_BUILD_JAVA_MEM
    export MMH_RAILS_BUILD_JAVA_OPTS="-Djava.awt.headless=true -Djruby.compile.mode=OFF -Djruby.launch.inproc=false $MMH_RAILS_BUILD_JAVA_OPTS"
    alias jrake="JAVA_MEM=\"$MMH_RAILS_BUILD_JAVA_MEM\" JAVA_OPTS=\"$MMH_RAILS_BUILD_JAVA_OPTS\" jruby -S rake"
    alias jspec="JAVA_MEM=\"$MMH_RAILS_BUILD_JAVA_MEM\" JAVA_OPTS=\"$MMH_RAILS_BUILD_JAVA_OPTS\" jruby script/spec"
  else
    echo "Error: Unsupported platform - $platform (maybe you should add support for it?)"
    exit 1
  fi

  alias cm="cd $MMH_HOME"
  alias cr="cd $MMH_HOME_RAILS"
  alias cj="cd $JBOSS_HOME"
  alias mysqlstart.mmh="sudo mysqld_safe --defaults-file=$DOTFILES/my.cnf.mmh 2>&1 > /dev/null &"
}
#function unload_mmh_env {


